# Site settings
title: "Omar Iraqi"
description: "Pentester Junior | Red Team | Active Directory | Web Security"
permalink: ':title:output_ext'

baseurl: ""   # site Ã  la racine (repo = omar-iraqi.github.io)
url: "https://omar-iraqi.github.io"

logo: "/assets/img/branding/logo-full.svg"
logo-icon: "/assets/img/branding/logo-icon.svg"
logo-icon-SEO: "/assets/img/branding/logo-icon-black.png"


# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Omar Iraqi # add your name
author-pic: Myself_Neon_grey.jpg
about-author: Pentester Junior | Red Team | Active Directory | Web

# Contact links
email: omar.iraqih@proton.me # Add your Email address
phone: #+33629782549 # Add your Phone number
website: https://omar-iraqi.github.io # Add your website
linkedin: %F0%9F%93%8Domar-i-a3679366/  # Add your Linkedin handle
github: omar-iraqi # Add your Github handle
twitter:  # Add your Twitter handle
bandcamp:  # Add your Bandcamp username
stackoverflow: # Add your stackoverflow account

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics: G-R8SZS2YBZK
fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
